[tool.poetry]
name = "advent-of-code"
version = "0.1.0"
description = ""
authors = ["vsedov <viv.sedov@hotmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
advent-of-code-data = "^1.2.2"
more-itertools = "^9.0.0"
icecream = "^2.1.3"
taskipy = "^1.10.3"


[tool.poetry.dev-dependencies]
black = "^22.10.0"
pytest = "^7.2.0"
pytest-cov = "^4.0.0"
pre-commit = "^2.20.0"
isort = "^5.10.1"
ruff = "^0.0.149"

[tool.poetry.plugins."adventofcode.user"]
vsedov = "aoc_cj:solve"

[tool.black]
line_length = 120

[tool.isort]
known_first_party = ["aoc_cj"]
line_length = 120
profile = "black"


[tool.pytest.ini_options]
# skip slow tests by default
addopts = "-m 'not slow'"
markers = [
    "slow: marks tests as slow"
]
xfail_strict=true

[tool.taskipy.tasks]
lint = "pre-commit run --all-files"
isort = "isort ."
freeze = "poetry export -f requirements.txt > requirements.txt --without-hashes"

[tool.pycln]
all = true


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
